project:
  type: website
  output-dir: _site

website:
  site-url: "https://kamran-arora.github.io/kamran-arora.github.io/"
  description: "Kamran's personal website"
  search: false

format:
  html:
    minimal: true
    theme: none
    css: styles.css
    toc: false
    anchor-sections: false
    code-copy: false

lang: en-GB
